title: 연구과제 관리 페이지
page-top-title: 연구과제 관리 페이지지
top-section-bg-text: 2025년 스마트돌봄서비스 이용자 적합성 조사
# home-subtitle: Sen Li&ensp;|&ensp;李森
# copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
